package main

// convert from CK sets to CS
var setMap = map[string]string{
	"Unlimited":                   "Unlimited Edition",
	"3rd Edition":                 "Revised Edition",
	"4th Edition":                 "Fourth Edition",
	"5th Edition":                 "Fifth Edition",
	"6th Edition":                 "Classic Sixth Edition",
	"7th Edition":                 "Seventh Edition",
	"8th Edition":                 "Eighth Edition",
	"9th Edition":                 "Ninth Edition",
	"10th Edition":                "Tenth Edition",
	"2010 Core Set":               "Magic 2010",
	"2011 Core Set":               "Magic 2011",
	"2012 Core Set":               "Magic 2012",
	"2013 Core Set":               "Magic 2013",
	"2014 Core Set":               "Magic 2014 Core Set",
	"2015 Core Set":               "Magic 2015 Core Set",
	"Archenemy - Nicol Bolas":     "Archenemy Nicol Bolas",
	"Battle Royale":               "Battle Royale Box Set",
	"Beatdown":                    "Beatdown Box Set",
	"Commander 2013":              "Commander 2013 Edition",
	"Commander Anthology Vol. II": "Commander Anthology 2018",
	"Conspiracy - Take the Crown": "Conspiracy Take the Crown",
	"Deckmaster":                  "Deckmasters",
	"Modern Event Deck":           "Modern Event Deck 2014",
	"Modern Masters 2015":         "Modern Masters 2015 Edition",
	"Modern Masters 2017":         "Modern Masters 2017 Edition",
	"Planechase 2012":             "Planechase 2012 Edition",
	"Portal 3K":                   "Portal Three Kingdoms",
	"Portal II":                   "Portal Second Age",
	"Ravnica":                     "Ravnica City of Guilds",
	"Shadows Over Innistrad":      "Shadows over Innistrad",
	"Shards of Alara":             "Shards Of Alara",
	"Timeshifted":                 "Time Spiral Timeshifted",
}

// CS attaches a different custom tag to the card name
var promoTags = map[string]string{
	"All Is Dust":              "Grand Prix promo",
	"Angel Demon":              "Double sided Helvault token",
	"Arena":                    "HarperPrism",
	"Azorius Guildmage":        "",
	"Batterskull":              "Grand Prix promo",
	"Black Sun's Zenith":       "Mirrodin Promo",
	"Blood Knight":             "Champs 2007",
	"Bramblewood Paragon":      "Champs 2008",
	"Breaking Entering":        "Dragon's Maze Promo",
	"Budoka Pupil":             "Kamigawa promo",
	"Call of the Herd":         "Grand Prix promo",
	"Chief Engineer":           "M15 Promo",
	"Chrome Mox":               "Grand Prix promo",
	"Counterspell":             "DCI Legend",
	"Cryptborn Horror":         "Ravnica Promo",
	"Dictate of Kruphix":       "Nyx game day promo",
	"Dictate of the Twin Gods": "Nyx Launch Promo",
	"Dimir Guildmage":          "Ravnica release promo",
	"Diregraf Ghoul":           "Innistrad Promo",
	"Doran, the Siege Tower":   "Champs 2007",
	"Dryad Militant":           "Ravnica promo",
	"Dungrove Elder":           "M12 Promo",
	"Earwig Squad":             "Morningtide Promo",
	"Eidolon of Blossoms":      "Promo",
	"Electrolyze":              "Champs 2006",
	"Elite Inquisitor":         "Innistrad Promo",
	"Evil Presents":            "",
	"Faerie Conclave":          "Commander Promo",
	"Figure of Destiny":        "Eventide Promo",
	"Firemane Avenger":         "Gatecrash Promo",
	"Flamerush Rider":          "alt art foil",
	"Force of Nature":          "Ninth Ed Promo",
	"Fruitcake Elemental":      "",
	"Garruk's Horde":           "M12 Promo",
	"Ghost-Lit Raider":         "Saviors promo",
	"Giant Badger":             "HarperPrism",
	"Gifts Given":              "",
	"Goblin Diplomats":         "M14 Promo",
	"Goblin Guide":             "Grand Prix promo",
	"Groundbreaker":            "Champs 2007",
	"Gruul Guildmage":          "Guildpact release promo",
	"Hall of Triumph":          "Nyx Game Day Promo",
	"Hedge Troll":              "Planar Chaos promo",
	"Heir of the Wilds":        "KoT Promo",
	"Hive Stirrings":           "M14 Promo",
	"Imperious Perfect":        "Ext Art",
	"Incinerate":               "DCI Legend",
	"Killing Wave":             "Avacyn Promo",
	"Kiora's Follower":         "Born of the Gods Promo",
	"Knight of New Alara":      "Alara Promo",
	"Latch Seeker":             "Avacyn Promo",
	"Liliana's Specter":        "M11 Promo",
	"Lotus Cobra":              "Grand Prix promo",
	"Ludevic's Test Subject":   "Innistrad Promo",
	"Maelstrom Pulse":          "Grand Prix promo",
	"Magmaquake":               "M13 Promo",
	"Mana Crypt":               "HarperPrism",
	"Mardu Shadowspear":        "Fate Reforged game day",
	"Memnite":                  "Scars Promo",
	"Mirran Crusader":          "",
	"Mitotic Slime":            "M11 Promo",
	"Mondronen Shaman":         "Dark Ascension promo",
	"Mutavault":                "Champs 2008",
	"Mwonvuli Beast Tracker":   "M13 Promo",
	"Myr Superion":             "New Phyrexia Promo",
	"Nalathni Dragon":          "Duelist",
	"Naughty Nice":             "",
	"Nighthowler":              "Theros promo",
	"Niv-Mizzet, the Firemind": "Champs 2006",
	"Pain Seer":                "Born of the Gods Promo",
	"Phalanx Leader":           "Theros promo",
	"Priest of Urabrask":       "New Phyrexia Promo",
	"Primeval Titan":           "Grand Prix promo",
	"Pristine Talisman":        "New Phyrexia Promo",
	"Rakdos Guildmage":         "Champs 2006",
	"Reclamation Sage":         "M15 Promo",
	"Restoration Angel":        "Avacyn Promo",
	"Reya Dawnbringer":         "Tenth Ed Promo",
	"Robot Chicken":            "San Diego PTQ Special Guest Promo",
	"Rukh Egg":                 "Eighth Ed Promo",
	"Sandsteppe Mastodon":      "Fate Reforged promo",
	"Scent of Cinder":          "Duelist",
	"Season's Beatings":        "",
	"Serra Avenger":            "Champs 2006",
	"Sewers of Estark":         "HarperPrism",
	"Shamanic Revelation":      "Fate Reforged promo",
	"Shivan Dragon":            "Ninth Ed Promo",
	"Shriekmaw":                "Lorwyn promo",
	"Snow Mercy":               "",
	"Spiritmonger":             "Grand Prix promo",
	"Sprouting Thrinax":        "DCI alt art foil",
	"Squelching Leeches":       "Nyx game day promo",
	"Staff of Nin":             "M13 Promo",
	"Stocking Tiger":           "",
	"Storm Entity":             "Future Sight Promo",
	"Stormblood Berserker":     "M12 Promo",
	"Strangleroot Geist":       "Dark Ascension Promo",
	"Sudden Shock":             "Time Spiral Promo",
	"Supplant Form":            "Fate Reforged promo",
	"Suture Priest":            "New Phyrexia Promo",
	"Sylvan Caryatid":          "Theros Promo",
	"Tempered Steel":           "Scars Promo",
	"The Destined":             "Nyx Launch Party Promo",
	"Treasure Mage":            "Mirrodin Promo",
	"Treetop Village":          "Promo",
	"Trostani's Summoner":      "Dragon's Maze Promo",
	"Umezawa's Jitte":          "Grand Prix promo",
	"Urza's Factory":           "Champs 2006",
	"Utter End":                "KoT Promo",
	"Vengevine":                "World Cup Promo",
	"Vexing Shusher":           "Shadowmoor Promo",
	"Voidslime":                "Champs 2006",
	"Windseeker Centaur":       "HarperPrism",
	"Woolly Thoctar":           "DCI alt art foil",
	"Yule Ooze":                "",
	"Zameck Guildmage":         "Gatecrash promo",
	"Zombie Apocalypse":        "Dark Ascension Promo",
}

var prereleaseTags = map[string]string{
	"Ancient Hellkite":             "M11 Promo",
	"Ant Queen":                    "M10 Promo",
	"Ass Whuppin'":                 "Release promo",
	"Brutal Hordechief":            "promo foil",
	"Colossal Whale":               "M14 Promo",
	"Deadbridge Goliath":           "Ravnica Promo",
	"Goblin Rabblemaster":          "M15 Promo",
	"Icy Blast":                    "promo",
	"In Garruk's Wake":             "M15 Promo",
	"Indulgent Tormentor":          "M15 Promo",
	"Joraga Warcaller":             "Worldwake Promo",
	"Lord of Shatterskull Pass":    "Eldrazi Promo",
	"Mardu Strike Leader":          "stamped foil",
	"Mercurial Pretender":          "M15 Promo",
	"Obelisk of Alara":             "Conflux Promo",
	"Phyrexian Metamorph":          "New Phyrexia Promo",
	"Phytotitan":                   "M15 Promo",
	"Resolute Archangel":           "M15 Promo",
	"Siege Dragon":                 "M15 Promo",
	"Skarrg Goliath":               "Gatecrash Promo",
	"Thopter Assembly":             "Mirrodin Promo",
	"Tromokratis":                  "Born of the Gods Promo",
	"Valakut, the Molten Pinnacle": "Zendikar Promo",
}

var gatewayTags = map[string]string{
	"Auramancer":               "Gateway Promo",
	"Bloodcrazed Neonate":      "Gateway Promo",
	"Boggart Ram-Gang":         "Gateway 2008",
	"Boneyard Wurm":            "Gateway Promo",
	"Boomerang":                "Gateway 2007",
	"Calciderm":                "Gateway 2007",
	"Cenn's Tactician":         "Gateway 2008",
	"Circle of Flame":          "Gateway Promo",
	"Curse of the Bloody Tome": "Gateway Promo",
	"Curse of Thirst":          "Gateway Promo",
	"Curse of Wizardry":        "Gateway special",
	"Dauntless Dourbark":       "Gateway special",
	"Deathless Angel":          "Gateway special",
	"Duergar Hedge-Mage":       "Gateway 2008",
	"Emeria Angel":             "Gateway special",
	"Fiery Temper":             "Gateway 2006",
	"Fling":                    "Gateway special",
	"Gather the Townsfolk":     "Gateway Promo",
	"Golem's Heart":            "Gateway special",
	"Gravedigger":              "Gateway 2008",
	"Hada Freeblade":           "Gateway special",
	"Hellspark Elemental":      "Gateway 2008",
	"Icatian Javelineers":      "Gateway 2006",
	"Kalastria Highborn":       "Gateway special",
	"Kor Duelist":              "Gateway special",
	"Kor Firewalker":           "Gateway special",
	"Lava Axe":                 "Gateway 2008",
	"Leatherback Baloth":       "Gateway special",
	"Llanowar Elves":           "Gateway 2007",
	"Marisi's Twinclaws":       "Gateway 2008",
	"Master's Call":            "Gateway special",
	"Maul Splicer":             "Gateway special",
	"Mind Control":             "Gateway 2009",
	"Mind Stone":               "Gateway 2007",
	"Mogg Fanatic":             "Gateway 2007",
	"Mycoid Shepherd":          "Gateway 2009",
	"Naya Sojourners":          "2010 Game Day",
	"Nearheath Stalker":        "Gateway Promo",
	"Nissa's Chosen":           "Gateway special",
	"Oona's Blackguard":        "Gateway 2008",
	"Path to Exile":            "Gateway 2008",
	"Pathrazer of Ulamog":      "Gateway special",
	"Plague Myr":               "Gateway special",
	"Plague Stinger":           "Gateway special",
	"Reckless Wurm":            "Gateway 2008",
	"Rise from the Grave":      "Gateway 2009",
	"Selkie Hedge Mage":        "Gateway 2008",
	"Shrine of Burning Rage":   "Gateway promo",
	"Signal Pest":              "Gateway special",
	"Skinrender":               "Gateway special",
	"Slave of Bolas":           "Gateway 2009",
	"Sprouting Thrinax":        "Gateway 2008",
	"Staggershock":             "Gateway special",
	"Sylvan Ranger":            "Gateway special",
	"Syphon Mind":              "Gateway WPN Promo",
	"Tormented Soul":           "Gateway Promo",
	"Vampire Nighthawk":        "Gateway special",
	"Vault Skirge":             "Gateway special",
	"Wilt-Leaf Cavalier":       "Gateway 2008",
	"Wood Elves":               "Gateway 2006",
	"Woolly Thoctar":           "Gateway 2008",
	"Yixlid Jailer":            "Gateway 2007",
	"Zoetic Cavern":            "Gateway 2007",
}

var arenaYears = map[string]int{
	"Arc Lightning":            2002,
	"Ashnod's Coupon":          2004,
	"Bonesplitter":             2003,
	"Booster Tutor":            2004,
	"Castigate":                2006,
	"Chill":                    2000,
	"Circle of Protection Art": 2004,
	"Coiling Oracle":           2006,
	"Creeping Mold":            2001,
	"Darksteel Ingot":          2004,
	"Dauthi Slayer":            2002,
	"Diabolic Edict":           2001,
	"Disenchant":               1996,
	"Dismiss":                  2001,
	"Duress":                   2000,
	"Elvish Aberration":        2003,
	"Empyrial Armor":           2001,
	"Enlightened Tutor":        2000,
	"Fireball":                 1996,
	"Fling":                    2001,
	"Gaea's Blessing":          2001,
	"Genju of the Spires":      2005,
	"Glacial Ray":              2004,
	"Goblin Mime":              2004,
	"Granny's Payback":         2004,
	"Karn, Silver Golem":       1999,
	"Man-o'-War":               2002,
	"Mana Leak":                2002,
	"Mise":                     2004,
	"Okina Nightwatch":         2005,
	"Pillage":                  2000,
	"Pouncing Jaguar":          1999,
	"Rewind":                   1999,
	"Serum Visions":            2004,
	"Skirk Marauder":           2003,
	"Skittering Skirge":        1999,
	"Skyknight Legionnaire":    2005,
	"Stupor":                   2000,
	"Surging Flame":            2006,
	"Uktabi Orangutan":         2000,
	"Wee Dragonauts":           2006,
}

var fnmYears = map[string]string{
	"Accumulated Knowledge":    "(FNM 2004)",
	"Acidic Slime":             "(FNM 2012)",
	"Albino Troll":             "(FNM 2002)",
	"Anathemancer":             "(FNM 2010)",
	"Ancient Grudge":           "(FNM 2012)",
	"Ancient Ziggurat":         "(FNM 2010)",
	"Armadillo Cloak":          "(FNM 2006)",
	"Arrogant Wurm":            "(FNM 2006)",
	"Artisan of Kozilek":       "(FNM 2011)",
	"Astral Slide":             "(FNM 2006)",
	"Aura of Silence":          "(FNM 2002)",
	"Avacyn's Pilgrim":         "(FNM 2012)",
	"Avalanche Riders":         "(FNM 2004)",
	"Banisher Priest":          "(FNM 2014)",
	"Basking Rootwalla":        "(FNM 2007)",
	"Beast of Burden":          "", // I hate you
	"Black Knight":             "(FNM 2002)",
	"Blastoderm":               "(FNM 2005)",
	"Bloodbraid Elf":           "(FNM 2010)",
	"Bottle Gnomes":            "(FNM 2003)",
	"Brain Maggot":             "(promo)",
	"Brainstorm":               "(FNM 2004)",
	"Browbeat":                 "(FNM 2009)",
	"Cabal Coffers":            "(FNM 2007)",
	"Cabal Therapy":            "(FNM 2005)",
	"Call of the Conclave":     "(FNM 2013)",
	"Capsize":                  "(FNM 2003)",
	"Carnophage":               "(FNM 2001)",
	"Carrion Feeder":           "(FNM 2004)",
	"Chainer's Edict":          "(FNM 2006)",
	"Circle of Protection Red": "(FNM 2005)",
	"Circular Logic":           "(FNM 2006)",
	"Cloudpost":                "(FNM 2010)",
	"Contagion Clasp":          "(FNM 2011)",
	"Counterspell":             "(FNM 2005)",
	"Cultivate":                "(FNM 2011)",
	"Deep Analysis":            "(FNM 2007)",
	"Desert":                   "(FNM 2008)",
	"Despise":                  "(FNM 2012)",
	"Dimir Charm":              "(FNM 2013)",
	"Disenchant":               "(FNM 2003)",
	"Dismember":                "(FNM 2012)",
	"Dissipate":                "(FNM 2002)",
	"Dissolve":                 "(FNM 2014)",
	"Drain Life":               "(FNM 2002)",
	"Duress":                   "(FNM 2005)",
	"Elves of Deep Shadow":     "(FNM 2006)",
	"Elvish Mystic":            "(FNM 2014)",
	"Elvish Visionary":         "(FNM 2010)",
	"Encroaching Wastes":       "(FNM 2014)",
	"Engineered Plague":        "(FNM 2007)",
	"Eternal Witness":          "(FNM 2008)",
	"Everflowing Chalice":      "(FNM 2011)",
	"Evolving Wilds":           "(FNM 2012)",
	"Experiment One":           "(FNM 2013)",
	"Fact or Fiction":          "(FNM 2005)",
	"Farseek":                  "(FNM 2013)",
	"Fire Ice":                 "(FNM 2006)",
	"Fireblast":                "(FNM 2001)",
	"Firebolt":                 "(FNM 2007)",
	"Fireslinger":              "(FNM 2002)",
	"Flametongue Kavu":         "(FNM 2005)",
	"Forbid":                   "(FNM 2002)",
	"Forbidden Alchemy":        "(FNM 2012)",
	"Force Spike":              "(FNM 2007)",
	"Frenzied Goblin":          "(promo)",
	"Gatekeeper of Malakir":    "(FNM 2010)",
	"Gerrard's Verdict":        "(FNM 2007)",
	"Ghor-Clan Rampager":       "(FNM 2013)",
	"Ghostly Prison":           "(FNM 2010)",
	"Giant Growth":             "(FNM 2000)",
	"Gitaxian Probe":           "(FNM 2012)",
	"Glistener Elf":            "(FNM 2012)",
	"Go for the Throat":        "(FNM 2011)",
	"Goblin Bombardment":       "(FNM 2003)",
	"Goblin Legionnaire":       "(FNM 2007)",
	"Goblin Ringleader":        "(FNM 2007)",
	"Goblin Warchief":          "(FNM 2006)",
	"Grisly Salvage":           "(FNM 2013)",
	"Icy Manipulator":          "(FNM 2005)",
	"Impulse":                  "(FNM 2001)",
	"Isochron Scepter":         "(FNM 2008)",
	"Izzet Charm":              "(FNM 2013)",
	"Jace's Ingenuity":         "(FNM 201", // I hate you more
	"Jackal Pup":               "(FNM 2001)",
	"Judge's Familiar":         "(FNM 2013)",
	"Juggernaut":               "(FNM 2005)",
	"Kird Ape":                 "(FNM 2005)",
	"Kitchen Finks":            "(FNM 2009)",
	"Krosan Grip":              "(FNM 2010)",
	"Krosan Tusker":            "(FNM 2003)",
	"Krosan Warchief":          "(FNM 2004)",
	"Life Death":               "(FNM 2006)",
	"Lightning Greaves":        "(FNM 2009)",
	"Lightning Rift":           "(FNM 2004)",
	"Lingering Souls":          "(FNM 2012)",
	"Llanowar Elves":           "(FNM 2000)",
	"Lobotomy":                 "(FNM 2006)",
	"Longbow Archer":           "(FNM 2000)",
	"Magma Jet":                "(FNM 2009)",
	"Merrow Reejerey":          "(FNM 2009)",
	"Mind Warp":                "(FNM 2000)",
	"Mogg Fanatic":             "(FNM 2002)",
	"Mother of Runes":          "(FNM 2004)",
	"Mulldrifter":              "(FNM 2009)",
	"Murderous Redcap":         "(FNM 2009)",
	"Muscle Sliver":            "(FNM 2003)",
	"Myr Enforcer":             "(FNM 2009)",
	"Oblivion Ring":            "(FNM 2009)",
	"Ophidian":                 "(FNM 2001)",
	"Pendelhaven":              "(FNM 2008)",
	"Pillar of Flame":          "(FNM 2012)",
	"Priest of Titania":        "(FNM 2003)",
	"Prodigal Sorcerer":        "(FNM 2000)",
	"Qasali Pridemage":         "(FNM 2010)",
	"Quirion Ranger":           "(FNM 2001)",
	"Rakdos Cackler":           "(FNM 2013)",
	"Rancor":                   "(FNM 2005)",
	"Reanimate":                "(FNM 2004)",
	"Reliquary Tower":          "(FNM 2013)",
	"Remand":                   "(FNM 2008)",
	"Resurrection":             "(FNM 2008)",
	"Rhox War Monk":            "(FNM 2011)",
	"Rift Bolt":                "(FNM 2010)",
	"River Boa":                "(FNM 2000)",
	"Roar of the Wurm":         "(FNM 2007)",
	"Sakura-Tribe Elder":       "(FNM 2009)",
	"Savage Lands":             "(FNM 2011)",
	"Scragnoth":                "(FNM 2003)",
	"Seal of Cleansing":        "(FNM 2005)",
	"Searing Spear":            "(FNM 2013)",
	"Serrated Arrows":          "(FNM 2008)",
	"Shock":                    "(FNM 2000)",
	"Shrapnel Blast":           "(FNM 2008)",
	"Silver Knight":            "(FNM 2004)",
	"Sin Collector":            "(FNM 2013)",
	"Slice and Dice":           "(FNM 2004)",
	"Smother":                  "(FNM 2003)",
	"Soltari Priest":           "(FNM 2002)",
	"Sparksmith":               "(FNM 2003)",
	"Spellstutter Sprite":      "(FNM 2011)",
	"Spike Feeder":             "(FNM 2002)",
	"Squadron Hawk":            "(FNM 2011)",
	"Staunch Defenders":        "(FNM 2000)",
	"Stoke the Flames":         "(FNM 2014)",
	"Stone Rain":               "(FNM 2000)",
	"Swords to Plowshares":     "(FNM 2001)",
	"Tectonic Edge":            "(FNM 2012)",
	"Teetering Peaks":          "(FNM 2011)",
	"Tendrils of Agony":        "(FNM 2008)",
	"Terminate":                "(FNM 2006)",
	"Terror":                   "(FNM 2000)",
	"Thirst for Knowledge":     "(FNM 2008)",
	"Tidehollow Sculler":       "(FNM 2010)",
	"Tormented Hero":           "(FNM 2014)",
	"Tormod's Crypt":           "(FNM 2008)",
	"Treetop Village":          "(FNM 2004)",
	"Volcanic Geyser":          "(FNM 2000)",
	"Wall of Blossoms":         "(FNM 2002)",
	"Wall of Omens":            "(FNM 2011)",
	"Wall of Roots":            "(FNM 2008)",
	"Warleader's Helix":        "(FNM 2013)",
	"Watchwolf":                "(FNM 2009)",
	"Whipcorder":               "(FNM 2003)",
	"White Knight":             "(FNM 2002)",
	"Wild Mongrel":             "(FNM 2006)",
	"Wild Nacatl":              "(FNM 2010)",
	"Willbender":               "(FNM 2004)",
	"Wing Shards":              "(FNM 2007)",
	"Withered Wretch":          "(FNM 2003)",
	"Wonder":                   "(FNM 2007)",
	"Wren's Run Vanquisher":    "(FNM 2009)",
}

var aetherMess = map[string]string{
	"Aether Adept":              "Æther Adept",
	"Aether Barrier":            "Æther Barrier",
	"Aether Burst":              "Æther Burst",
	"Aether Charge":             "Æther Charge",
	"Aether Figment":            "Æther Figment",
	"Aether Flash":              "Æther Flash",
	"Aether Gale":               "Æther Gale",
	"Aether Membrane":           "Æther Membrane",
	"Aether Mutation":           "Æther Mutation",
	"Aether Rift":               "Æther Rift",
	"Aether Searcher":           "Æther Searcher",
	"Aether Snap":               "Æther Snap",
	"Aether Spellbomb":          "Æther Spellbomb",
	"Aether Sting":              "Æther Sting",
	"Aether Storm":              "Æther Storm",
	"Aether Tide":               "Æther Tide",
	"Aether Tradewinds":         "Æther Tradewinds",
	"Aether Vial":               "Æther Vial",
	"Aether Web":                "Æther Web",
	"Aetherflame Wall":          "Ætherflame Wall",
	"Aetherize":                 "Ætherize",
	"Aetherling":                "Ætherling",
	"Aethermage's Touch":        "Æthermage's Touch",
	"Aetherplasm":               "Ætherplasm",
	"Aethersnatch":              "Æthersnatch",
	"Aethersnipe":               "Æthersnipe",
	"Aetherspouts":              "Ætherspouts",
	"Aethertow":                 "Æthertow",
	"Anchor to the Aether":      "Anchor to the Æther",
	"Arm with Aether":           "Arm with Æther",
	"Azorius Aethermage":        "Azorius Æthermage",
	"Chaotic Aether":            "Chaotic Æther",
	"Fold into Aether":          "Fold into Æther",
	"Frozen Aether":             "Frozen Æther",
	"Gate to the Aether":        "Gate to the Æther",
	"Ghirapur Aether Grid":      "Ghirapur Æther Grid",
	"Obscuring Aether":          "Obscuring Æther",
	"Scornful Aether Lich":      "Scornful Æther Lich",
	"Surging Aether":            "Surging Æther",
	"Tainted AEther":            "Tainted Æther",
	"The Aether Flues":          "The Æther Flues",
	"Unravel the Aether":        "Unravel the Æther",
	"Vedalken Aethermage":       "Vedalken Æthermage",
	"Vedalken AEthermage":       "Vedalken Æthermage",
	"Yet Another Aether Vortex": "Yet Another Æther Vortex",
}

var urzaLands = map[string]map[string]string{
	"Urza's Power Plant (Bug)": map[string]string{
		"Antiquities": "Urza's Power Plant (bug)",
		"Chronicles":  "Urza's Power Plant (Version 1)",
	},
	"Urza's Power Plant (Columns)": map[string]string{
		"Antiquities": "Urza's Power Plant (columns)",
		"Chronicles":  "Urza's Power Plant (Version 2)",
	},
	"Urza's Power Plant (Sphere)": map[string]string{
		"Antiquities": "Urza's Power Plant (sphere)",
		"Chronicles":  "Urza's Power Plant (Version 3)",
	},
	"Urza's Power Plant (Pot)": map[string]string{
		"Antiquities": "Urza's Power Plant (rock in pot)",
		"Chronicles":  "Urza's Power Plant (Version 4)",
	},
	"Urza's Tower (Forest)": map[string]string{
		"Antiquities": "Urza's Tower (forest)",
		"Chronicles":  "Urza's Tower (Version 1)",
	},
	"Urza's Tower (Mountains)": map[string]string{
		"Antiquities": "Urza's Tower (mountain)",
		"Chronicles":  "Urza's Tower (Version 2)",
	},
	"Urza's Tower (Plains)": map[string]string{
		"Antiquities": "Urza's Tower (plains)",
		"Chronicles":  "Urza's Tower (Version 3)",
	},
	"Urza's Tower (Shore)": map[string]string{
		"Antiquities": "Urza's Tower (shore)",
		"Chronicles":  "Urza's Tower (Version 4)",
	},
	"Urza's Mine (Sphere)": map[string]string{
		"Antiquities": "Urza's Mine (claw sphere)",
		"Chronicles":  "Urza's Mine (Version 1)",
	},
	"Urza's Mine (Mouth)": map[string]string{
		"Antiquities": "Urza's Mine (mouth)",
		"Chronicles":  "Urza's Mine (Version 2)",
	},
	"Urza's Mine (Pulley)": map[string]string{
		"Antiquities": "Urza's Mine (pulley)",
		"Chronicles":  "Urza's Mine (Version 3)",
	},
	"Urza's Mine (Tower)": map[string]string{
		"Antiquities": "Urza's Mine (tower)",
		"Chronicles":  "Urza's Mine (Version 4)",
	},
}

var anyVariant = map[string]string{
	// accents
	"Dandan":          "Dandân",
	"Ghazban Ogre":    "Ghazbán Ogre",
	"Ghazban Ogress":  "Ghazbán Ogress",
	"Ifh-Biff Efreet": "Ifh Bíff Efreet",
	"Junun Efreet":    "Junún Efreet",
	"Juzam Djinn":     "Juzám Djinn",
	"Khabal Ghoul":    "Khabál Ghoul",
	"Ring of Ma'ruf":  "Ring of MaRuf",
	"Seance":          "Séance",

	// split cards
	"Discovery": "Discovery Dispersal",
	"Flower":    "Flower Flourish",

	// capitals (and dashes)
	"Aerathi Berserker":               "Ærathi Berserker",
	"Blind with Anger":                "Blind With Anger",
	"Boggart Ram-Gang (Gateway 2008)": "Boggart Ram- Gang (Gateway 2008)",
	"Honor-Worn Shaku":                "Honor worn Shaku",
	"Man-o'-War (Arena 2002)":         "Man O' War (Arena 2002)",
	"Nezumi Bone-Reader":              "Nezumi Bone reader",
	"Soratami Mirror-Guard":           "Soratami Mirror guard",
	"Soratami Mirror-Mage":            "Soratami Mirror mage",

	// keep as is
	"Boggart Ram-Gang":          "",
	"Elspeth, Knight-Errant":    "",
	"Ink-Eyes, Servant of Oni":  "",
	"Kiki-Jiki, Mirror Breaker": "",
	"Siege-Gang Commander":      "",

	// variants
	"Arcane Denial (Axe)":             "Arcane Denial (Version 2)",
	"Arcane Denial (Sword)":           "Arcane Denial",
	"Brothers Yamazaki (160 A)":       "", //skip
	"Brothers Yamazaki (160 B)":       "Brothers Yamazaki",
	"Elvish Ranger (Facing Left)":     "Elvish Ranger",
	"Elvish Ranger (Facing Right)":    "Elvish Ranger (Version 2)",
	"Feast or Famine (Falling)":       "Feast or Famine (Version 2)",
	"Feast or Famine (Knife)":         "Feast or Famine",
	"Gorilla Shaman (Facing Left)":    "Gorilla Shaman",
	"Gorilla Shaman (Facing Right)":   "Gorilla Shaman (Version 2)",
	"High Tide (Maddocks)":            "High Tide (Version 2)",
	"High Tide (Tucker)":              "High Tide",
	"High Tide (Weber)":               "High Tide (Version 3)",
	"Hymn to Tourach (Danforth)":      "Hymn to Tourach (Version 2)",
	"Hymn to Tourach (Hoover)":        "Hymn to Tourach (Version 3)",
	"Hymn to Tourach (Kirschner)":     "Hymn to Tourach (Version 4)",
	"Hymn to Tourach (Van Camp)":      "Hymn to Tourach",
	"Mishra's Factory (Autumn)":       "Mishra's Factory (fall)",
	"Mishra's Factory (Spring)":       "Mishra's Factory (spring)",
	"Mishra's Factory (Summer)":       "Mishra's Factory (summer)",
	"Mishra's Factory (Winter)":       "Mishra's Factory (winter)",
	"Simic Signet (215 A)":            "Simic Signet",
	"Simic Signet (216 B)":            "Simic Signet",
	"Soldevi Adnate (One Eye)":        "Soldevi Adnate",
	"Soldevi Adnate (Two Eyes)":       "Soldevi Adnate (Version 2)",
	"Solemn Simulacrum (218 A)":       "Solemn Simulacrum",
	"Solemn Simulacrum (219 B)":       "Solemn Simulacrum",
	"Strip Mine (A)":                  "Strip Mine (Version 3)",
	"Strip Mine (B)":                  "Strip Mine (Version 1)",
	"Strip Mine (C)":                  "Strip Mine (Version 4)",
	"Strip Mine (D)":                  "Strip Mine (Version 2)",
	"Temple of the False God (271 A)": "Temple of the False God",
	"Temple of the False God (272 B)": "Temple of the False God",
}

var guildKitCards = map[string]string{
	"Isperia, Supreme Judge":          "Azorius",
	"Pride of the Clouds":             "Azorius",
	"Lavinia of the Tenth":            "Azorius",
	"Windreaver":                      "Azorius",
	"Isperia the Inscrutable":         "Azorius",
	"Archon of the Triumvirate":       "Azorius",
	"Judge's Familiar":                "Azorius",
	"Azorius Guildmage":               "Azorius",
	"Azorius Herald":                  "Azorius",
	"Stoic Ephemera":                  "Azorius",
	"Court Hussar":                    "Azorius",
	"Hover Barrier":                   "Azorius",
	"Lyev Skyknight":                  "Azorius",
	"Azorius Justiciar":               "Azorius",
	"Skymark Roc":                     "Azorius",
	"Sky Hussar":                      "Azorius",
	"Sphinx of Foresight":             "Azorius",
	"Spirit of the Spires":            "Azorius",
	"Sphinx of New Prahv":             "Azorius",
	"Windstorm Drake":                 "Azorius",
	"Detention Sphere":                "Azorius",
	"Dovescape":                       "Azorius",
	"Sky Tether":                      "Azorius",
	"Render Silent":                   "Azorius",
	"Sphinx's Revelation":             "Azorius",
	"Azorius Charm":                   "Azorius",
	"Dramatic Rescue":                 "Azorius",
	"Unbreakable Formation":           "Azorius",
	"Summary Judgment":                "Azorius",
	"Sphinx's Insight":                "Azorius",
	"Warrant Warden":                  "Azorius",
	"Depose Deploy":                   "Azorius",
	"Azorius Signet":                  "Azorius",
	"Azorius Keyrune":                 "Azorius",
	"Azorius Chancery":                "Azorius",
	"Azorius Guildgate":               "Azorius",
	"Rakdos, Lord of Riots":           "Rakdos",
	"Lyzolda, the Blood Witch":        "Rakdos",
	"Avatar of Discord":               "Rakdos",
	"Rakdos Pit Dragon":               "Rakdos",
	"Master of Cruelties":             "Rakdos",
	"Carnival Hellsteed":              "Rakdos",
	"Rakdos the Defiler":              "Rakdos",
	"Utvara Hellkite":                 "Rakdos",
	"Rakdos Cackler":                  "Rakdos",
	"Thrill-Kill Assassin":            "Rakdos",
	"Rakdos Guildmage":                "Rakdos",
	"Rakdos Shred-Freak":              "Rakdos",
	"Splatter Thug":                   "Rakdos",
	"Jagged Poppet":                   "Rakdos",
	"Crypt Champion":                  "Rakdos",
	"Rix Maadi Reveler":               "Rakdos",
	"Spawn of Mayhem":                 "Rakdos",
	"Rakdos Firewheeler":              "Rakdos",
	"Blade Juggler ":                  "Rakdos",
	"Dreadbore":                       "Rakdos",
	"Demonfire":                       "Rakdos",
	"Rakdos's Return":                 "Rakdos",
	"Skewer the Critics":              "Rakdos",
	"Dead Revels":                     "Rakdos",
	"Rakdos Charm":                    "Rakdos",
	"Auger Spree":                     "Rakdos",
	"Cackling Flames":                 "Rakdos",
	"Wrecking Ball":                   "Rakdos",
	"Carnival Carnage":                "Rakdos",
	"Rakdos Signet":                   "Rakdos",
	"Rakdos Keyrune":                  "Rakdos",
	"Riot Spikes":                     "Rakdos",
	"Theater of Horrors":              "Rakdos",
	"Rakdos Carnarium":                "Rakdos",
	"Rakdos Guildgate":                "Rakdos",
	"Ruric Thar, the Unbowed":         "Gruul",
	"Birds of Paradise":               "Gruul",
	"Burning-Tree Shaman":             "Gruul",
	"Ulasht, the Hate Seed":           "Gruul",
	"Rumbling Slum":                   "Gruul",
	"Giant Solifuge":                  "Gruul",
	"Rubblebelt Raiders":              "Gruul",
	"Skarrgan Firebird":               "Gruul",
	"Rubblehulk":                      "Gruul",
	"Protean Hulk":                    "Gruul",
	"Borborygmos":                     "Gruul",
	"Savageborn Hydra":                "Gruul",
	"Skarrgan Pit-Skulk":              "Gruul",
	"Wasteland Viper":                 "Gruul",
	"Scab-Clan Mauler":                "Gruul",
	"Zhur-Taa Druid":                  "Gruul",
	"Burning-Tree Emissary":           "Gruul",
	"Ghor-Clan Rampager":              "Gruul",
	"Zhur-Taa Swine":                  "Gruul",
	"Immolation Shaman":               "Gruul",
	"Ravager Wurm":                    "Gruul",
	"Clan Guildmage":                  "Gruul",
	"Zhur-Taa Goblin":                 "Gruul",
	"Sunder Shaman":                   "Gruul",
	"Savage Twister":                  "Gruul",
	"Gruul Charm":                     "Gruul",
	"Pit Fight":                       "Gruul",
	"Flames of the Raze-Boar":         "Gruul",
	"Collision Colossus":              "Gruul",
	"Gruul Signet":                    "Gruul",
	"Wurmweaver Coil":                 "Gruul",
	"Cindervines":                     "Gruul",
	"Rhythm of the Wild":              "Gruul",
	"Gruul Guildgate":                 "Gruul",
	"Gruul Turf":                      "Gruul",
	"Vorel of the Hull Clade":         "Simic",
	"Gyre Sage":                       "Simic",
	"Vinelasher Kudzu":                "Simic",
	"Cytoplast Root-Kin":              "Simic",
	"Fathom Mage":                     "Simic",
	"Omnibian":                        "Simic",
	"Momir Vig, Simic Visionary":      "Simic",
	"Progenitor Mimic":                "Simic",
	"Experiment Kraj":                 "Simic",
	"Simic Sky Swallower":             "Simic",
	"Experiment One":                  "Simic",
	"Cloudfin Raptor":                 "Simic",
	"Coiling Oracle":                  "Simic",
	"Zameck Guildmage":                "Simic",
	"Elusive Krasis":                  "Simic",
	"Plaxcaster Frogling":             "Simic",
	"Trygon Predator":                 "Simic",
	"Nimbus Swimmer":                  "Simic",
	"Zegana, Utopian Speaker":         "Simic",
	"Skitter Eel":                     "Simic",
	"Frilled Mystic":                  "Simic",
	"Trollbred Guardian":              "Simic",
	"Galloping Lizrog":                "Simic",
	"Miming Slime":                    "Simic",
	"Urban Evolution":                 "Simic",
	"Voidslime":                       "Simic",
	"Rapid Hybridization":             "Simic",
	"Applied Biomancy":                "Simic",
	"Simic Signet":                    "Simic",
	"Simic Ascendancy":                "Simic",
	"Guardian Project":                "Simic",
	"Simic Guildgate":                 "Simic",
	"Simic Growth Chamber":            "Simic",
	"Teysa, Orzhov Scion":             "Orzhov",
	"Orzhov Pontiff":                  "Orzhov",
	"Ghost Council of Orzhova":        "Orzhov",
	"Pontiff of Blight":               "Orzhov",
	"Skeletal Vampire":                "Orzhov",
	"Treasury Thrull":                 "Orzhov",
	"Deathpact Angel":                 "Orzhov",
	"Angel of Despair":                "Orzhov",
	"Martyred Rusalka":                "Orzhov",
	"Plagued Rusalka":                 "Orzhov",
	"Vizkopa Guildmage":               "Orzhov",
	"Sin Collector":                   "Orzhov",
	"Keening Banshee":                 "Orzhov",
	"Belfry Spirit":                   "Orzhov",
	"Teysa Karlov":                    "Orzhov",
	"Orzhov Enforcer":                 "Orzhov",
	"Imperious Oligarch":              "Orzhov",
	"Pitiless Pontiff":                "Orzhov",
	"Ministrant of Obligation":        "Orzhov",
	"Vindictive Vampire":              "Orzhov",
	"Basilica Bell-Haunt":             "Orzhov",
	"Ultimate Price":                  "Orzhov",
	"Orzhov Charm":                    "Orzhov",
	"Mortify":                         "Orzhov",
	"Final Payment":                   "Orzhov",
	"Consecrate Consume":              "Orzhov",
	"Orzhov Signet":                   "Orzhov",
	"Debtors' Knell":                  "Orzhov",
	"Stab Wound":                      "Orzhov",
	"Pillory of the Sleepless":        "Orzhov",
	"One Thousand Lashes":             "Orzhov",
	"Smothering Tithe":                "Orzhov",
	"Ethereal Absolution":             "Orzhov",
	"Orzhov Basilica":                 "Orzhov",
	"Orzhov Guildgate":                "Orzhov",
	"Etrata, the Silencer":            "Dimir",
	"Lazav, Dimir Mastermind":         "Dimir",
	"Dimir Doppelganger":              "Dimir",
	"Nightveil Specter":               "Dimir",
	"Circu, Dimir Lobotomist":         "Dimir",
	"Consuming Aberration":            "Dimir",
	"Mirko Vosk, Mind Drinker":        "Dimir",
	"Szadek, Lord of Secrets":         "Dimir",
	"Wall of Mist":                    "Dimir",
	"Dimir Guildmage":                 "Dimir",
	"Moroii":                          "Dimir",
	"Netherborn Phalanx":              "Dimir",
	"Dinrova Horror":                  "Dimir",
	"Blood Operative":                 "Dimir",
	"Barrier of Bones":                "Dimir",
	"Nightveil Predator":              "Dimir",
	"Glimpse the Unthinkable":         "Dimir",
	"Stolen Identity":                 "Dimir",
	"Call of the Nightwing":           "Dimir",
	"Ribbons of Night":                "Dimir",
	"Mephitic Vapors":                 "Dimir",
	"Notion Rain":                     "Dimir",
	"Disdainful Stroke":               "Dimir",
	"Telling Time":                    "Dimir",
	"Last Gasp":                       "Dimir",
	"Dimir Charm":                     "Dimir",
	"Warped Physique":                 "Dimir",
	"Syncopate":                       "Dimir",
	"Mission Briefing":                "Dimir",
	"Unexplained Disappearance":       "Dimir",
	"Price of Fame":                   "Dimir",
	"Discovery Dispersal":             "Dimir",
	"Dimir Signet":                    "Dimir",
	"Dimir Aqueduct":                  "Dimir",
	"Dimir Guildgate":                 "Dimir",
	"Trostani, Selesnya's Voice":      "Selesnya",
	"Loxodon Hierarch":                "Selesnya",
	"Armada Wurm":                     "Selesnya",
	"Tolsimir Wolfblood":              "Selesnya",
	"Dryad Militant":                  "Selesnya",
	"Selesnya Evangel":                "Selesnya",
	"Watchwolf":                       "Selesnya",
	"Selesnya Guildmage":              "Selesnya",
	"Centaur Healer":                  "Selesnya",
	"Siege Wurm":                      "Selesnya",
	"Venerated Loxodon":               "Selesnya",
	"Vernadi Shieldmate":              "Selesnya",
	"Conclave Cavalier":               "Selesnya",
	"Hour of Reckoning":               "Selesnya",
	"Call of the Conclave":            "Selesnya",
	"Camaraderie":                     "Selesnya",
	"Advent of the Wurm":              "Selesnya",
	"Gather Courage":                  "Selesnya",
	"Selesnya Charm":                  "Selesnya",
	"Sundering Growth":                "Selesnya",
	"Devouring Light":                 "Selesnya",
	"Scatter the Seeds":               "Selesnya",
	"Bounty of Might":                 "Selesnya",
	"Selesnya Signet":                 "Selesnya",
	"Glare of Subdual":                "Selesnya",
	"Growing Ranks":                   "Selesnya",
	"Privileged Position":             "Selesnya",
	"Pollenbright Wings":              "Selesnya",
	"Conclave Tribunal":               "Selesnya",
	"Grove of the Guardian":           "Selesnya",
	"Selesnya Guildgate":              "Selesnya",
	"Selesnya Sanctuary":              "Selesnya",
	"Niv-Mizzet, the Firemind":        "Izzet",
	"Tibor and Lumia":                 "Izzet",
	"Hypersonic Dragon":               "Izzet",
	"Djinn Illuminatus":               "Izzet",
	"Goblin Electromancer":            "Izzet",
	"Nivix Guildmage":                 "Izzet",
	"Guttersnipe":                     "Izzet",
	"Gelectrode":                      "Izzet",
	"Wee Dragonauts":                  "Izzet",
	"Erratic Cyclops":                 "Izzet",
	"Electrostatic Field":             "Izzet",
	"Crackling Drake":                 "Izzet",
	"Mizzium Mortars":                 "Izzet",
	"Stitch in Time":                  "Izzet",
	"Invoke the Firemind":             "Izzet",
	"Shattering Spree":                "Izzet",
	"Goblin Rally":                    "Izzet",
	"Quasiduplicate":                  "Izzet",
	"Direct Current":                  "Izzet",
	"Beacon Bolt":                     "Izzet",
	"Char":                            "Izzet",
	"Cerebral Vortex":                 "Izzet",
	"Electrickery":                    "Izzet",
	"Pyromatics":                      "Izzet",
	"Izzet Charm":                     "Izzet",
	"Thunderheads":                    "Izzet",
	"Electrolyze":                     "Izzet",
	"Radical Idea":                    "Izzet",
	"Chemister's Insight":             "Izzet",
	"Turn Burn":                       "Izzet",
	"Izzet Signet":                    "Izzet",
	"Firemind's Research":             "Izzet",
	"Izzet Boilerworks":               "Izzet",
	"Izzet Guildgate":                 "Izzet",
	"Aurelia, the Warleader":          "Boros",
	"Boros Reckoner":                  "Boros",
	"Legion Loyalist":                 "Boros",
	"Firemane Avenger":                "Boros",
	"Spark Trooper":                   "Boros",
	"Agrus Kos, Wojek Veteran":        "Boros",
	"Firemane Angel":                  "Boros",
	"Razia, Boros Archangel":          "Boros",
	"Frenzied Goblin":                 "Boros",
	"Boros Elite":                     "Boros",
	"Bomber Corps":                    "Boros",
	"Daring Skyjek":                   "Boros",
	"Boros Swiftblade":                "Boros",
	"Sunhome Guildmage":               "Boros",
	"Skyknight Legionnaire":           "Boros",
	"Swiftblade Vindicator":           "Boros",
	"Legion Warboss":                  "Boros",
	"Light of the Legion":             "Boros",
	"Sunhome Stalwart":                "Boros",
	"Wojek Bodyguard":                 "Boros",
	"Blade Instructor":                "Boros",
	"Hammer Dropper":                  "Boros",
	"Brightflame":                     "Boros",
	"Gird for Battle":                 "Boros",
	"Sworn Companions":                "Boros",
	"Master Warcraft":                 "Boros",
	"Boros Charm":                     "Boros",
	"Lightning Helix":                 "Boros",
	"Martial Glory":                   "Boros",
	"Boros Signet":                    "Boros",
	"Boros Keyrune":                   "Boros",
	"Boros Garrison":                  "Boros",
	"Boros Guildgate":                 "Boros",
	"Sunhome, Fortress of the Legion": "Boros",
	"Izoni, Thousand-Eyed":            "Golgari",
	"Jarad, Golgari Lich Lord":        "Golgari",
	"Deathrite Shaman":                "Golgari",
	"Lotleth Troll":                   "Golgari",
	"Deadbridge Goliath":              "Golgari",
	"Savra, Queen of the Golgari":     "Golgari",
	"Grave-Shell Scarab":              "Golgari",
	"Sisters of Stone Death":          "Golgari",
	"Elves of Deep Shadow":            "Golgari",
	"Korozda Guildmage":               "Golgari",
	"Stinkweed Imp":                   "Golgari",
	"Shambling Shell":                 "Golgari",
	"Slum Reaper":                     "Golgari",
	"Charnel Troll":                   "Golgari",
	"Hatchery Spider":                 "Golgari",
	"Glowspore Shaman":                "Golgari",
	"Plaguecrafter":                   "Golgari",
	"Rhizome Lurcher":                 "Golgari",
	"Golgari Findbroker":              "Golgari",
	"Gaze of Granite":                 "Golgari",
	"Drown in Filth":                  "Golgari",
	"Treasured Find":                  "Golgari",
	"Vigor Mortis":                    "Golgari",
	"Abrupt Decay":                    "Golgari",
	"Darkblast":                       "Golgari",
	"Golgari Charm":                   "Golgari",
	"Grisly Salvage":                  "Golgari",
	"Putrefy":                         "Golgari",
	"Necrotic Wound":                  "Golgari",
	"Status Statue":                   "Golgari",
	"Golgari Signet":                  "Golgari",
	"Deadbridge Chant":                "Golgari",
	"Golgari Guildgate":               "Golgari",
	"Golgari Rot Farm":                "Golgari",
}

var dashingSets = []string{
	"Alliances",
	"Anthologies",
	"Antiquities",
	"Arabian Nights",
	"Archenemy",
	"Battle Royale Box Set",
	"Betrayers of Kamigawa",
	"Champions of Kamigawa",
	"Chronicles",
	"Classic Sixth Edition",
	"Coldsnap",
	"Conflux",
	"Darksteel",
	"Dissension",
	"Duel Decks Garruk vs. Liliana",
	"Eighth Edition",
	"Eventide",
	"Exodus",
	"Fate Reforged",
	"Fifth Dawn",
	"Fifth Edition",
	"Fourth Edition",
	"From the Vault Dragons",
	"Future Sight",
	"Guildpact",
	"Homelands",
	"Ice Age",
	"Invasion",
	"Legends",
	"Lorwyn",
	"Mercadian Masques",
	"Mirrodin",
	"Morningtide",
	"Nemesis",
	"Ninth Edition",
	"Odyssey",
	"Planechase",
	"Portal Three Kingdoms",
	"Portal",
	"Prerelease Stamped",
	"Promotional Gateway",
	"Promotional Jr Super Series",
	"Promotional Other",
	"Prophecy",
	"Ravnica City of Guilds",
	"Revised Edition",
	"Rise of the Eldrazi",
	"Scourge",
	"Shadowmoor",
	"Shards Of Alara",
	"Starter 1999",
	"Tempest",
	"Tenth Edition",
	"Time Spiral Timeshifted",
	"Time Spiral",
	"Torment",
	"Urza's Legacy",
	"Urza's Saga",
	"Visions",
	"Zendikar",
}

var skippablePromos = []string{
	"15th Anniversary Foil",
	"Alternate Art",
	"April 29 Prerelease",
	"Book Promo",
	"Booth Foil",
	"Clash Pack Foil",
	"Clash Pack Foils",
	"Convention Foil",
	"DCI Foil (#69)",
	"Draft Weekend Foil",
	"Dragonfury Promo",
	"Duels Promo Foil",
	"Duels of the Planeswalkers 2014 Foil",
	"Duels of the Planeswalkers Foil",
	"Duels of the Planeswalkers PS3 Promo Foil",
	"Duels of the Planeswalkers Steam Promo Foil",
	"Duels of the Planeswalkers Xbox Promo Foil",
	"Game Day Extended Art Foil",
	"Game Day Extended Art",
	"Game Day Foil",
	"German Misprint",
	"Gift Box Foil",
	"Hascon Promo Foil",
	"IDW Comic Promo",
	"Intro Pack Rare Foil",
	"Japanese Jace vs. Chandra Foil",
	"Junior APAC Series",
	"MC Qualifier Foil",
	"Magic League Foil",
	"MagicFest Foil",
	"MagicFest Non-Foil",
	"Media Insert Foil",
	"Nationals",
	"Open House Foil",
	"OpenHouse",
	"Planeswalker Weekend Foil",
	"Pro Tour Foil",
	"RPTQ Promo Foil",
	"Resale Foil",
	"Store Championship Foil",
	"Store Championship Foil",
	"Store Foil",
	"Store Promo Foil",
	"Ugin's Fate",
	"WMC Qualifier",
	"WMCQ Foil",
	"WPN - #70",
	"Duels Promo",
	"Duels of the Planeswalkers 2014 Foil",
	"Ponies: The Galloping",
	"Redeem Foil",
	"Welcome 2016",
	"XBox Promo",
}
